-- Generated by tools/adjudication_export.py from experiments/out/*.json.
-- Do not edit by hand. 数字与产物对账由生成器保证;哈希/适配器集映射:
--   codeId 0 = efb8e95
--   codeId 1 = e22d5d8
--   codeId 2 = 621fbd6
--   codeId 3 = 46af286
--   codeId 4 = 554370b
--   codeId 5 = 4aa4347
--   codeId 6 = 16421ad
--   codeId 7 = efc5375
--   codeId 8 = 2ea4ab3
--   codeId 9 = 12648fe
import WitCert.Adjudication

namespace WitCert.Adjudication

def q6o : Run := ⟨fun | .workers => 1 | .ring128 => 513 | .ring4 => 513 | .codeTag => 0 | .seed => 42 | .probeSet => 0 | .evict128 => 0 | .evict4 => 0 | .ablateExtra => 0 | .decodeTranslate => 0, 1000⟩
-- ^ q6o_graphb2.json  code=efb8e95 acc=1.000
def q6n : Run := ⟨fun | .workers => 4 | .ring128 => 513 | .ring4 => 513 | .codeTag => 0 | .seed => 42 | .probeSet => 0 | .evict128 => 216 | .evict4 => 215 | .ablateExtra => 0 | .decodeTranslate => 0, 750⟩
-- ^ q6n_graphb2.json  code=efb8e95 acc=0.750
def q6p2 : Run := ⟨fun | .workers => 4 | .ring128 => 513 | .ring4 => 513 | .codeTag => 1 | .seed => 42 | .probeSet => 0 | .evict128 => 480 | .evict4 => 480 | .ablateExtra => 0 | .decodeTranslate => 0, 583⟩
-- ^ q6p2_graphb2.json  code=e22d5d8 acc=0.583
def q6p3ring1025 : Run := ⟨fun | .workers => 4 | .ring128 => 1025 | .ring4 => 1025 | .codeTag => 1 | .seed => 42 | .probeSet => 0 | .evict128 => 0 | .evict4 => 0 | .ablateExtra => 0 | .decodeTranslate => 0, 1000⟩
-- ^ q6p3_ring1025.json  code=e22d5d8 acc=1.000
def q6p3ring513 : Run := ⟨fun | .workers => 4 | .ring128 => 513 | .ring4 => 513 | .codeTag => 1 | .seed => 42 | .probeSet => 0 | .evict128 => 256 | .evict4 => 256 | .ablateExtra => 0 | .decodeTranslate => 0, 833⟩
-- ^ q6p3_ring513.json  code=e22d5d8 acc=0.833
def q6p5c128 : Run := ⟨fun | .workers => 4 | .ring128 => 513 | .ring4 => 1025 | .codeTag => 1 | .seed => 42 | .probeSet => 0 | .evict128 => 256 | .evict4 => 0 | .ablateExtra => 0 | .decodeTranslate => 0, 1000⟩
-- ^ q6p5_c128small.json  code=e22d5d8 acc=1.000
def q6p5c4 : Run := ⟨fun | .workers => 4 | .ring128 => 1025 | .ring4 => 513 | .codeTag => 1 | .seed => 42 | .probeSet => 0 | .evict128 => 0 | .evict4 => 353 | .ablateExtra => 0 | .decodeTranslate => 0, 667⟩
-- ^ q6p5_c4small.json  code=e22d5d8 acc=0.667
def q6p6c128 : Run := ⟨fun | .workers => 4 | .ring128 => 513 | .ring4 => 1025 | .codeTag => 2 | .seed => 42 | .probeSet => 1 | .evict128 => 224 | .evict4 => 0 | .ablateExtra => 0 | .decodeTranslate => 0, 1000⟩
-- ^ q6p6_c128evict.json  code=621fbd6 acc=1.000
def q6p6c4 : Run := ⟨fun | .workers => 4 | .ring128 => 1025 | .ring4 => 513 | .codeTag => 2 | .seed => 42 | .probeSet => 1 | .evict128 => 0 | .evict4 => 289 | .ablateExtra => 0 | .decodeTranslate => 0, 750⟩
-- ^ q6p6_c4evict.json  code=621fbd6 acc=0.750
def q6p7c128 : Run := ⟨fun | .workers => 4 | .ring128 => 513 | .ring4 => 1025 | .codeTag => 3 | .seed => 42 | .probeSet => 1 | .evict128 => 188 | .evict4 => 0 | .ablateExtra => 0 | .decodeTranslate => 0, 1000⟩
-- ^ q6p7_c128evict.json  code=46af286 acc=1.000
def q6p7c4 : Run := ⟨fun | .workers => 4 | .ring128 => 1025 | .ring4 => 513 | .codeTag => 3 | .seed => 42 | .probeSet => 1 | .evict128 => 0 | .evict4 => 227 | .ablateExtra => 0 | .decodeTranslate => 0, 917⟩
-- ^ q6p7_c4evict.json  code=46af286 acc=0.917
def q6p9c4 : Run := ⟨fun | .workers => 4 | .ring128 => 1025 | .ring4 => 513 | .codeTag => 4 | .seed => 42 | .probeSet => 1 | .evict128 => 0 | .evict4 => 1030 | .ablateExtra => 0 | .decodeTranslate => 0, 417⟩
-- ^ q6p9_c4evict.json  code=554370b acc=0.417
def q6p10c4 : Run := ⟨fun | .workers => 4 | .ring128 => 1025 | .ring4 => 513 | .codeTag => 5 | .seed => 42 | .probeSet => 1 | .evict128 => 0 | .evict4 => 665 | .ablateExtra => 0 | .decodeTranslate => 0, 500⟩
-- ^ q6p10_c4evict.json  code=4aa4347 acc=0.500
def q6p11c4 : Run := ⟨fun | .workers => 4 | .ring128 => 1025 | .ring4 => 513 | .codeTag => 6 | .seed => 42 | .probeSet => 0 | .evict128 => 0 | .evict4 => 293 | .ablateExtra => 0 | .decodeTranslate => 0, 750⟩
-- ^ q6p11_c4evict.json  code=16421ad acc=0.750
def q6p11c128 : Run := ⟨fun | .workers => 4 | .ring128 => 513 | .ring4 => 1025 | .codeTag => 6 | .seed => 42 | .probeSet => 0 | .evict128 => 288 | .evict4 => 0 | .ablateExtra => 0 | .decodeTranslate => 0, 1000⟩
-- ^ q6p11_c128evict.json  code=16421ad acc=1.000
def q6p14ablate : Run := ⟨fun | .workers => 4 | .ring128 => 1025 | .ring4 => 513 | .codeTag => 7 | .seed => 42 | .probeSet => 0 | .evict128 => 0 | .evict4 => 560 | .ablateExtra => 1 | .decodeTranslate => 0, 0⟩
-- ^ q6p14_ablate.json  code=efc5375 acc=0.000
def q6p14ctl : Run := ⟨fun | .workers => 4 | .ring128 => 1025 | .ring4 => 513 | .codeTag => 7 | .seed => 42 | .probeSet => 0 | .evict128 => 0 | .evict4 => 419 | .ablateExtra => 0 | .decodeTranslate => 0, 667⟩
-- ^ q6p14_control.json  code=efc5375 acc=0.667
def q11bg : Run := ⟨fun | .workers => 1 | .ring128 => 1025 | .ring4 => 129 | .codeTag => 8 | .seed => 42 | .probeSet => 0 | .evict128 => 0 | .evict4 => 224 | .ablateExtra => 0 | .decodeTranslate => 0, 250⟩
-- ^ q11b_graphb2.json  code=2ea4ab3 acc=0.250
def q11t2fix : Run := ⟨fun | .workers => 1 | .ring128 => 1025 | .ring4 => 129 | .codeTag => 9 | .seed => 42 | .probeSet => 0 | .evict128 => 0 | .evict4 => 20 | .ablateExtra => 0 | .decodeTranslate => 1, 1000⟩
-- ^ q11t2_r129fix.json  code=12648fe acc=1.000
def q11t2ctl : Run := ⟨fun | .workers => 1 | .ring128 => 1025 | .ring4 => 129 | .codeTag => 9 | .seed => 42 | .probeSet => 0 | .evict128 => 0 | .evict4 => 20 | .ablateExtra => 0 | .decodeTranslate => 0, 500⟩
-- ^ q11t2_r129ctl.json  code=12648fe acc=0.500

end WitCert.Adjudication
