-- Generated by tools/release_export.py. Do not edit by hand.
-- 数据 = 发布清单/论文/脚本的机械实算;裁决在 ReleaseGate.lean。
import WitCert.ReleaseCalculus

namespace WitCert.Release

/-- p1-kv-certificates:refs 14 条,附录坐标 34 个,仓名出现 3 处,dest 冲突 0,终验越界读 0。 -/
def snapshot_p1 : Snapshot := {
  residualLeaks := 0,
  refs := [⟨"formal/check_standalone.sh", true⟩, ⟨"reproduce.sh", true⟩, ⟨"tools/make_canon.py", true⟩, ⟨"tests/test_paper_claims.py", true⟩, ⟨"tools/make_figs.py", true⟩, ⟨"tests/test_certificates.py", true⟩, ⟨"tests/test_independent_crosscheck.py", true⟩, ⟨"formal/check_all.sh", true⟩, ⟨"papers/p1-kv-certificates/theorems.json", true⟩, ⟨"experiments/out_siteB/rrd_w2a_qwen7b.json", true⟩, ⟨"papers/p1-kv-certificates/canon.json", true⟩, ⟨"papers/p1-kv-certificates/CANON.md", true⟩, ⟨"papers/p1-kv-certificates/THEOREMS.md", true⟩, ⟨"tests/canon_unsourced_baseline.json", true⟩],
  thmLines := [38, 23, 57, 127, 34, 51, 158, 82, 75, 109, 127, 57, 140, 64, 65, 79, 121, 114, 87, 82, 36, 52, 90, 32, 85, 79, 25, 54, 57, 39, 69, 16, 42, 14],
  repoNames := [("witcert-kv-certificates", "witcert-kv-certificates"), ("witcert-kv-certificates", "witcert-kv-certificates"), ("witcert-kv-certificates", "witcert-kv-certificates")],
  destCollisions := 0,
  dynOutsideReads := 0 }

/-- p2-attention-memory:refs 13 条,附录坐标 157 个,仓名出现 4 处,dest 冲突 0,终验越界读 0。 -/
def snapshot_p2 : Snapshot := {
  residualLeaks := 0,
  refs := [⟨"reproduce.sh", true⟩, ⟨"tools/make_canon.py", true⟩, ⟨"tests/test_paper_claims.py", true⟩, ⟨"tools/p2_figs.py", true⟩, ⟨"experiments/flagship_gate.py", true⟩, ⟨"experiments/p98_concurrent_identity.py", true⟩, ⟨"formal/check_all.sh", true⟩, ⟨"formal/check_standalone.sh", true⟩, ⟨"papers/p2-attention-memory/theorems.tex", true⟩, ⟨"papers/p2-attention-memory/figdata.json", true⟩, ⟨"formal/WitCert/AdjudicationData.lean", true⟩, ⟨"papers/p2-attention-memory/main.tex", true⟩, ⟨"tests/canon_unsourced_baseline.json", true⟩],
  thmLines := [143, 89, 66, 204, 37, 144, 112, 127, 65, 118, 93, 36, 160, 93, 273, 268, 661, 745, 146, 803, 832, 470, 71, 257, 241, 510, 176, 757, 672, 713, 770, 692, 40, 53, 28, 204, 311, 611, 376, 420, 531, 105, 568, 522, 59, 81, 91, 101, 173, 206, 97, 130, 220, 113, 69, 51, 48, 45, 56, 75, 84, 213, 169, 210, 234, 132, 195, 86, 39, 57, 223, 111, 184, 73, 51, 34, 72, 443, 515, 387, 452, 79, 408, 51, 201, 414, 41, 399, 495, 556, 310, 359, 107, 542, 96, 102, 113, 86, 117, 226, 47, 54, 56, 66, 81, 145, 100, 94, 111, 79, 128, 89, 212, 190, 184, 204, 59, 48, 79, 45, 106, 716, 784, 723, 418, 129, 206, 844, 904, 950, 920, 505, 189, 853, 208, 821, 758, 737, 866, 225, 188, 390, 634, 977, 1049, 67, 73, 79, 362, 886, 70, 144, 235, 445, 548, 271, 666],
  repoNames := [("witprobe-attention-memory", "witprobe-attention-memory"), ("witprobe-attention-memory", "witprobe-attention-memory"), ("witcert-kv-certificates", "witcert-kv-certificates"), ("witprobe-attention-memory", "witprobe-attention-memory")],
  destCollisions := 0,
  dynOutsideReads := 0 }

/-- p3-witcert-v:refs 7 条,附录坐标 0 个,仓名出现 2 处,dest 冲突 0,终验越界读 0。 -/
def snapshot_p3 : Snapshot := {
  residualLeaks := 0,
  refs := [⟨"tests/test_paper_claims.py", true⟩, ⟨"tools/p3_figs.py", true⟩, ⟨"formal/check_standalone.sh", true⟩, ⟨"formal/check_all.sh", true⟩, ⟨"papers/p3-witcert-v/theorems.json", true⟩, ⟨"papers/p3-witcert-v/main.tex", true⟩, ⟨"tests/canon_unsourced_baseline.json", true⟩],
  thmLines := [],
  repoNames := [("witcert-w-certified-precision", "witcert-w-certified-precision"), ("witcert-w-certified-precision", "witcert-w-certified-precision")],
  destCollisions := 0,
  dynOutsideReads := 0 }

/-- p4-moe-protect:refs 4 条,附录坐标 0 个,仓名出现 0 处,dest 冲突 0,终验越界读 0。 -/
def snapshot_p4 : Snapshot := {
  residualLeaks := 0,
  refs := [⟨"tests/test_paper_claims.py", true⟩, ⟨"formal/check_standalone.sh", true⟩, ⟨"papers/p4-moe-protect/main.tex", true⟩, ⟨"tests/canon_unsourced_baseline.json", true⟩],
  thmLines := [],
  repoNames := [],
  destCollisions := 0,
  dynOutsideReads := 0 }

end WitCert.Release
