-- Generated by tools/release_export.py. Do not edit by hand.
-- 数据 = 发布清单/论文/脚本的机械实算;裁决在 ReleaseGate.lean。
import WitCert.ReleaseCalculus

namespace WitCert.Release

/-- p1-kv-certificates:refs 13 条,附录坐标 20 个,仓名出现 3 处,dest 冲突 0,终验越界读 0。 -/
def snapshot_p1 : Snapshot := {
  residualLeaks := 0,
  refs := [⟨"formal/check_standalone.sh", true⟩, ⟨"reproduce.sh", true⟩, ⟨"tools/make_canon.py", true⟩, ⟨"tests/test_paper_claims.py", true⟩, ⟨"tools/make_figs.py", true⟩, ⟨"tests/test_certificates.py", true⟩, ⟨"tests/test_independent_crosscheck.py", true⟩, ⟨"formal/check_all.sh", true⟩, ⟨"papers/p1-kv-certificates/theorems.json", true⟩, ⟨"papers/p1-kv-certificates/canon.json", true⟩, ⟨"papers/p1-kv-certificates/CANON.md", true⟩, ⟨"papers/p1-kv-certificates/THEOREMS.md", true⟩, ⟨"tests/canon_unsourced_baseline.json", true⟩],
  thmLines := [38, 23, 57, 127, 34, 82, 36, 52, 90, 32, 85, 79, 25, 54, 57, 39, 69, 16, 42, 14],
  repoNames := [("witcert-kv-certificates", "witcert-kv-certificates"), ("witcert-kv-certificates", "witcert-kv-certificates"), ("witcert-kv-certificates", "witcert-kv-certificates")],
  destCollisions := 0,
  dynOutsideReads := 0 }

/-- p2-attention-memory:refs 16 条,附录坐标 67 个,仓名出现 4 处,dest 冲突 0,终验越界读 0。 -/
def snapshot_p2 : Snapshot := {
  residualLeaks := 0,
  refs := [⟨"reproduce.sh", true⟩, ⟨"tools/make_canon.py", true⟩, ⟨"tests/test_paper_claims.py", true⟩, ⟨"tools/p2_figs.py", true⟩, ⟨"experiments/flagship_gate.py", true⟩, ⟨"experiments/p98_concurrent_identity.py", true⟩, ⟨"formal/check_all.sh", true⟩, ⟨"formal/check_standalone.sh", true⟩, ⟨"papers/p1-kv-certificates/theorems.json", true⟩, ⟨"papers/p1-kv-certificates/canon.json", true⟩, ⟨"papers/p1-kv-certificates/CANON.md", true⟩, ⟨"papers/p2-attention-memory/theorems.tex", true⟩, ⟨"papers/p2-attention-memory/figdata.json", true⟩, ⟨"formal/WitCert/AdjudicationData.lean", true⟩, ⟨"papers/p2-attention-memory/main.tex", true⟩, ⟨"tests/canon_unsourced_baseline.json", true⟩],
  thmLines := [143, 89, 66, 204, 37, 144, 112, 127, 65, 118, 93, 35, 159, 92, 173, 73, 51, 34, 72, 443, 515, 387, 452, 79, 408, 51, 201, 414, 41, 399, 495, 556, 310, 359, 107, 542, 226, 47, 54, 56, 66, 81, 145, 100, 94, 111, 79, 128, 89, 212, 190, 184, 204, 59, 48, 79, 45, 106, 128, 189, 208, 225, 66, 72, 78, 69, 143],
  repoNames := [("witprobe-attention-memory", "witprobe-attention-memory"), ("witprobe-attention-memory", "witprobe-attention-memory"), ("witcert-kv-certificates", "witcert-kv-certificates"), ("witprobe-attention-memory", "witprobe-attention-memory")],
  destCollisions := 0,
  dynOutsideReads := 0 }

end WitCert.Release
