-- Generated by tools/release_export.py from dist/release_events.jsonl.
-- Do not edit by hand. 裁决定理在 ReleaseProtocolGate.lean。
import WitCert.ReleaseProtocol

namespace WitCert.Release

def journal : List Ev := [.verifyOk "p1-kv-certificates" "a2b099185cbe74b25d3d9d42b1481596d752f9104bd4418b7239020ad5b62f2a"]

/-- 本次推送尝试(无 pending 时恒 true)。 -/
def pendingOk : Bool := true

end WitCert.Release
