# -*- coding: utf-8 -*-
"""判别链数据导出:experiments/out/*.json → formal/WitCert/AdjudicationData.lean。

与 canon/theorems 同纪律:Lean 里的每个数字由本脚本从产物**机械导出**,
不许手写。acc 用千分点(‰,×1000 取整;曾误称 bp,单位更正 2026-08-05)
保持 Nat 可判定;代码哈希与适配器
集合映射为小整数 id(映射表一并写进生成文件供人工核对)。

python3 tools/adjudication_export.py
"""
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "experiments", "out")
DST = os.path.join(ROOT, "formal", "WitCert", "AdjudicationData.lean")

#: (lean 标识符, run_id, tag)。只导出判别链引用的轮次。
ROUNDS = [
    ("q6o",        "q6o",   "graphb2"),
    ("q6n",        "q6n",   "graphb2"),
    ("q6p2",       "q6p2",  "graphb2"),
    ("q6p3ring1025", "q6p3", "ring1025"),
    ("q6p3ring513",  "q6p3", "ring513"),
    ("q6p5c128",   "q6p5",  "c128small"),
    ("q6p5c4",     "q6p5",  "c4small"),
    ("q6p6c128",   "q6p6",  "c128evict"),
    ("q6p6c4",     "q6p6",  "c4evict"),
    ("q6p7c128",   "q6p7",  "c128evict"),
    ("q6p7c4",     "q6p7",  "c4evict"),
    ("q6p9c4",     "q6p9",  "c4evict"),
    ("q6p10c4",    "q6p10", "c4evict"),
    ("q6p11c4",    "q6p11", "c4evict"),
    ("q6p11c128",  "q6p11", "c128evict"),
    ("q6p14ablate", "q6p14", "ablate"),
    ("q6p14ctl",   "q6p14", "control"),
    ("q11bg",      "q11b",  "graphb2"),
    ("q11t2fix",   "q11t2", "r129fix"),
    ("q11t2ctl",   "q11t2", "r129ctl"),
]


def _rs(d, key):
    return ((d.get("snapshot") or {}).get(key) or {}).get("ring_stats", {})


def main():
    code_ids, adapter_ids = {}, {}
    lines = []
    for ident, rid, tag in ROUNDS:
        p = os.path.join(OUT, "%s_%s.json" % (rid, tag))
        if not os.path.exists(p):
            print("跳过(产物缺):", p)
            continue
        d = json.load(open(p, encoding="utf-8"))
        m = d.get("manifest") or {}
        code = m.get("code", "?")
        adapters = m.get("adapters", "")
        code_ids.setdefault(code, len(code_ids))
        adapter_ids.setdefault(adapters, len(adapter_ids))
        r128, r4 = _rs(d, "pool_swap"), _rs(d, "pool_swap_c4")
        # forensic 探针开关(时序扰动源,登记为混杂):产物自证口径
        probed = 1 if (r128.get("n_forensic_rows") or r4.get("n_forensic_rows")
                       or r128.get("n_evict_ahead") or r4.get("n_evict_ahead")) \
            else 0
        def _envn(k):
            # R6 注意:env 未设(用代码默认)记 0,与显式同值不同 ——
            # 保守方向(只会多拒绝不会放过),比较前应显式设 env
            v = str(m.get(k, ""))
            return int(v) if v.isdigit() else 0
        vals = {"workers": m.get("workers", 0), "ring128": _envn("ring_pages_env"),
                "ring4": _envn("c4_ring_pages_env"), "codeTag": code_ids[code],
                "seed": m.get("seed", 0), "probeSet": probed,
                "evict128": r128.get("n_evict", 0) or 0,
                "evict4": r4.get("n_evict", 0) or 0,
                "ablateExtra": 1 if (d.get("witcert_env") or {}).get(
                    "WITCERT_STAGEB_ABLATE_EXTRA") == "1" else 0,
                "decodeTranslate": 1 if (d.get("witcert_env") or {}).get(
                    "WITCERT_DECODE_TRANSLATE") == "1" else 0}
        body_fn = " | ".join(".%s => %d" % kv for kv in vals.items())
        lines.append("def %s : Run := ⟨fun | %s, %d⟩"
                     % (ident, body_fn, round(d["acc"] * 1000)))
        lines.append("-- ^ %s_%s.json  code=%s acc=%.3f" % (rid, tag, code, d["acc"]))
    body = [
        "-- Generated by tools/adjudication_export.py from experiments/out/*.json.",
        "-- Do not edit by hand. 数字与产物对账由生成器保证;哈希/适配器集映射:",
    ]
    for c, i in sorted(code_ids.items(), key=lambda x: x[1]):
        body.append("--   codeId %d = %s" % (i, c))
    body += ["import WitCert.Adjudication", "",
             "namespace WitCert.Adjudication", ""] + lines + [
             "", "end WitCert.Adjudication", ""]
    open(DST, "w", encoding="utf-8").write("\n".join(body))
    print("→ %s(%d 轮)" % (DST, len(lines) // 2))


if __name__ == "__main__":
    main()
